banner view implemented
Iterable/iterable-web-sdk pull request #213
Opened 2023-07-07 12:55 UTC by iamavishkar

## JIRA Ticket(s) if any

* [MOB-XXXX](https://iterable.atlassian.net/browse/MOB-XXXX)

## Description

## Test Steps

2023-07-07 14:11 UTC, Sagarpatel14 commented
![image](https://github.com/Iterable/iterable-web-sdk/assets/99024473/73eeddd1-d8fd-4177-891c-e8ef1fe10dcf)
![image](https://github.com/Iterable/iterable-web-sdk/assets/99024473/532f4a37-7492-421d-978b-80b905da7d8f)

2023-08-07 18:39 UTC, mprew97 requested changes
We need to pull this into a new page in the react example app `/components` and render it there so it can be seen/used in real time.

2023-08-07 18:39 UTC, mprew97 commented on src/components/banner/index.tsx
> +      </style>
i'd really like to find a decent library to implement granular css styles like this. can this not be passed in directly to the `style` props same as the others? As much as possible, would prefer to pull this out of the actual component tree.

2023-08-14 12:33 UTC, iamavishkar commented
request you to please review the PR as it has been updated.

2023-08-16 20:41 UTC, mprew97 commented
> request you to please review the PR as it has been updated.

Ty sir!

We should be able to just import the `Banner` component in `react-example` as a user would, as opposed to duplicating it. Can we do that and also have an example of it being displayed on a page somewhere in the example? Like an actual live component example?

2023-08-21 14:32 UTC, devcsomnicg commented
Hi @mprew97 here is the video for the same: https://drive.google.com/file/d/1ifip1OplImM9m2q-kOXGwxNwenqJXkCC/view?usp=sharing

2023-08-28 13:29 UTC, mprew97 approved these changes

2023-08-28 13:55 UTC, mprew97 commented
Once the build issues are resolved, we can merge this.

2023-10-19 14:59 UTC, mprew97 commented
Hi @devcsomnicg can we resolve the conflict here?

2023-11-22 14:24 UTC, merged