card view implemented
Iterable/iterable-web-sdk pull request #214
Opened 2023-07-07 12:57 UTC by iamavishkar

## JIRA Ticket(s) if any

* [MOB-XXXX](https://iterable.atlassian.net/browse/MOB-XXXX)

## Description

## Test Steps

2023-07-07 14:12 UTC, Sagarpatel14 commented
![image](https://github.com/Iterable/iterable-web-sdk/assets/99024473/ef3a36e3-5ce0-4c1e-b134-db6fe2f6c917)
![image](https://github.com/Iterable/iterable-web-sdk/assets/99024473/86d05d78-dc0f-4e35-abd1-6033b4f0552a)

2023-08-07 18:44 UTC, mprew97 requested changes
Please add this along with the other components to a `/components` page in the react-example app.

2023-08-07 18:44 UTC, mprew97 commented on src/components/card/index.tsx
> +const Card = (props: CardProps) => {
would prefer to keep this consistent with the other components and destructure the props either inline in the component declaration or just below.

2023-08-07 18:44 UTC, mprew97 commented on src/components/card/index.tsx
> +  const isPrimaryBtnDisabled = props.disablePrimaryBtn || false;
these should both just be `Boolean(someProp)`

2023-08-07 18:44 UTC, mprew97 commented on src/components/card/index.tsx
> +          }`}
Same comment as the other PR: it's preferred to keep styles out of the component tree as much as possible. if the `style` prop doesn't allow certain css in `style`, we should consider other options.

2023-08-16 20:40 UTC, mprew97 commented
> request you to please review the PR as it has been updated.

Ty sir!

We should be able to just import the `Card` component in `react-example` as a user would. Can we do that and also have an example of it being displayed on a page somewhere in the example? Like an actual live component example?

2023-08-21 14:31 UTC, devcsomnicg commented
Hi @mprew97 here is the video for the same:

https://drive.google.com/file/d/1ifip1OplImM9m2q-kOXGwxNwenqJXkCC/view?usp=sharing

2023-08-28 13:55 UTC, mprew97 commented
Please resolve the build issues here and then this can be merged.

2023-10-19 15:00 UTC, mprew97 commented
@devcsomnicg can we resolved the conflict here? happy to merge as soon as it's resolved.

2023-11-22 14:26 UTC, merged