Embedded msgs example
Iterable/iterable-web-sdk pull request #233
Opened 2023-09-18 06:42 UTC by devcsomnicg

## JIRA Ticket(s) if any

* [MOB-XXXX](https://iterable.atlassian.net/browse/MOB-XXXX)

## Description

## Test Steps

2023-10-19 15:01 UTC, mprew97 commented
@devcsomnicg can we resolve the conflicts here please? Will review after the changes have been pulled back in.

2023-11-06 14:00 UTC, mprew97 requested changes
Are we trashing the `Card notification` and `Banner notification` PRs? Notice the card component code is in here but there's been no conflict resolution on those old PRs. Please close those out if we don't intend to merge them separately (which is fine by me at this point).

2023-11-15 07:46 UTC, devcsomnicg commented on src/components/card/index.tsx
> +                : { ...defaultButtonStyles, ...secondaryBtnStyle }
Resolved.

2023-11-15 07:47 UTC, devcsomnicg commented on src/embedded/embeddedManager.ts
> +  // private notifyUpdateDelegates() {
Removed.

2023-11-15 07:49 UTC, devcsomnicg commented on react-example/src/views/EmbeddedMsgs.tsx
> +          messages.map((message: any, index: number) => (
Resolved.

2023-11-15 08:12 UTC, devcsomnicg commented on react-example/src/views/EmbeddedMsgs.tsx
> +              text={message.messages[0]?.elements?.text[0]?.text}
This will change once PR: https://github.com/Iterable/iterable-web-sdk/pull/243 will merge.

2023-11-15 14:24 UTC, mprew97 approved these changes

2023-11-15 14:24 UTC, merged