[MOB-9639] Added handler for notifying customer app of a newly created anon userid
Iterable/iterable-web-sdk pull request #460
Opened 2024-09-30 09:19 UTC by darshan-iterable

## JIRA Ticket(s) if any

* [MOB-9639](https://iterable.atlassian.net/browse/MOB-9639)

## Description
Add handlers for notifying customer app of a newly created Anon userid

[MOB-9639]: https://iterable.atlassian.net/browse/MOB-9639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-01 14:48 UTC, mprew97 approved these changes

2024-10-01 14:48 UTC, mprew97 requested changes
actually, can we make this a part of the config object mentioned [here](https://iterable.atlassian.net/browse/MOB-9578?atlOrigin=eyJpIjoiMzZjZGM1ZmEwM2MxNGZhYThmODczYjg3MDZjNjY1YTQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)? as in a part of the `identityResolution` object in the config?

2024-10-04 08:22 UTC, darshan-iterable commented
> actually, can we make this a part of the config object mentioned [here](https://iterable.atlassian.net/browse/MOB-9578?atlOrigin=eyJpIjoiMzZjZGM1ZmEwM2MxNGZhYThmODczYjg3MDZjNjY1YTQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)? as in a part of the `identityResolution` object in the config?

Moved `onAnonUserCreated` in `identityResolution` object in the config

2024-10-07 14:29 UTC, mprew97 approved these changes

2024-10-07 14:29 UTC, merged